nubisproject/nubis-base

packer/main.json, packer/release.json
=> see commits

Puppetfile, packer/main.json
Just add support for using iam_instance_profile="name" in variables,
as opposed to AWS secrets
=> add support for IAM instance profiles

packer/consul-autojoin.sh
=> use instance-id for node name

nubis/packer/main.json, nubis/puppet/README.mkd, nubis/puppet/consul.pp, nubis/puppet/fluentd.pp, nubis/puppet/init.pp, nubis/puppet/postfix.pp
=> move base puppet manifests in tree

Makefile, nubis/bin/release.sh
This reverts commit 7fd781a12812f093edf2750dd1f11090122207e8.
=> Revert "use jq to manage the release.json file"

.gitignore, README.md, nubis/bin/packer-bootstrap, nubis/builder/project.json
Addressed https://github.com/Nubisproject/nubis-base/issues/65
=> Addressing https://github.com/Nubisproject/nubis-base/issues/65

nubis/builder/project.json
This reverts commit c9b82b2d53c4c988aaa36827f27509c7a77b1107.
=> Revert "Revert "disable amazon-instance-ubuntu for now, ec2-upload-bundle is borked with IAM roles""

nubis/bin/packer-bootstrap, nubis/builder/project.json
https://github.com/Nubisproject/nubis-base/issues/84
=> Solving issue 84

nubis/bin/consul-autojoin.sh
All this now requires is :
NUBIS_ENVIRONMENT=sandbox
NUBIS_DOMAIN=nubis.allizom.org
in user-data, nothing else. Note that NUBIS_DOMAIN is new
=> Add consul-based auto-discovery-bootstrap juju.

nubis/Puppetfile
This commit adds a kibana3 puppet module from puppet forge.
=> adding kibana3 puppet module to Puppetfile for use in elk project

nubis/Puppetfile
I'll need this puppet module to create an OpenLDAP server
=> adding openldap module to Puppetfile

nubis/puppet/credstash.pp, nubis/puppet/init.pp
Fixes #152
Tested on Ubuntu & Amazon Linux
=> Include credstash in the base images

nubis/bin/packer-bootstrap
=> Disable Amazon Linux auto-updating in our base images, and make sure it stays disabled in derived images.

nubis/Puppetfile
=> Add nubis-puppet-eip module to Puppetfile

nubis/Puppetfile
=> Missing comma

nubis/puppet/consulate.pp, nubis/puppet/init.pp
=> Install consulate in base images

nubis/bin/consul-autojoin.sh
=> Remove port numbers from peers, as retry_join doesn't like it

nubis/bin/nubis-lib.sh
This is a simple library for regular patterns that we use in nubis, there isn't any plumbing to get it installed in our instances yet until it gets reviewed by @gozer and @tinnightcap 
This PR also fixes issue #67
=> [do-not-merge] [review-request] Nubis bash library

nubis/bin/consul-autojoin.sh
This is so Consul can bootstrap in a multiple account per VPC setup.
For DNS discovery, we need to be able to build a unique DNS endpoint
across all environments
Helps along nubisproject/nubis-consul#71
=> Add support for a new user-data variable, NUBIS_ACOUNT.

nubis/puppet/dnsmasq.pp
=> Prepend nameserver 127.0.0.1 if amazon linux

nubis/bin/consul-autojoin.sh
Helps along nubisproject/nubis-consul#71
=> Turn the Consul bootstrap script into something that's a lot more resilient to failures of all kinds.

CHANGELOG.md, nubis/Puppetfile
=> Update CHANGELOG for v1.0.0

nubis/Puppetfile
=> Version bump

nubis/puppet/files/fluentd.sysconfig, nubis/puppet/fluentd.pp, nubis/puppet/postfix.pp
=> Adjust logging for RedHat variants as well as Debian

nubis/puppet/fluentd.pp
=> Ensure we restart td-agent (fluent) as a watchdog cron job just in case of crash

nubis/puppet/fluentd.pp
=> fix typo, its source, not content

nubis/Puppetfile
This is only some cleanup but it helps resolve part of #209
=> Cleanup some modules that are not being used

nubis/puppet/confd.pp
Need to merge https://github.com/gozer/nubis-site_confd/pull/2 before we can merge this
=> confd version bump

nubis/Puppetfile
=> Remove Jenkins-specific puppet modules.

nubis/puppet/fluentd.pp
=> Pin fluent-plugin-ec2-metadata at 0.0.7 (latest)

nubis/puppet/mig.pp
=> Upgrade mig

nubis/files/confd/mig-agent.cfg.tmpl
=> Add a /config/relay_user Consul var, to configure the mig relay user

nubis/puppet/fluentd.pp
=> Ensure td-agent runs on root on ubuntu

nubis/puppet/mig.pp
=> Ensure lsb_release is installed (dependency for MiG)

nubis/puppet/confd.pp
=> Install a confd service watchdog.

nubis/puppet/init.pp
=> Remove simplistic node liveness health-check, it's failure prone and is useless

nubis/puppet/files/profile.d_proxy.sh
=> Add EC2 metadata service to no_proxies list

nubis/bin/consul-autojoin.sh
=> Restart confd once Consul is good to go

nubis/files/confd/mig-agent.cfg.tmpl
=> Make sure the default MiG API endpoint isn't '/' terminated

nubis/Puppetfile, nubis/puppet/consul.pp
=> Upgrade Consul to v0.6.0

nubis/puppet/dnsmasq.pp
=> Ensure dnsmasq doesnt start running during nubis builds

nubis/puppet/consul.pp, nubis/puppet/files/consul-bootstrap
=> Fix Consul startup on RHEL

nubis/puppet/startup.pp
=> More fixing, unfortunately our Puppet is apparently too old to follow symlinks like I was hoping.

nubis/puppet/files/consul-bootstrap
Fixes #262
See-Also: nubisproject/nubis-consul#109
=> Remove all Consul server specific bits out of out startup.

nubis/puppet/files/consul-bootstrap
=> Use /etc/consul/zzz-join.skip as an auto-join skipping flag file

nubis/puppet/credstash.pp, nubis/puppet/files/nubis-secret
=> Add nubis secret wrapper script, fixes issue #271

nubis/puppet/files/housekeeper, nubis/puppet/housekeeper.pp
=> Move the housekeeper script fron nubis-builder to here

nubis/puppet/files/consul-bootstrap
=> Restart confd once Consul is bootstrapped

nubis/puppet/confd.pp
=> Upgrade to confd 0.11.0

nubis/puppet/credstash.pp
https://github.com/fugue/credstash/releases/tag/v1.9.1
https://github.com/fugue/credstash/releases/tag/v1.9.0
=> Upgrade to credstash 1.9.1

nubis/files/confd/mig-agent.cfg.tmpl, nubis/puppet/mig.pp
Update version, and also include new configuration parameter setting for
agent instance metadata discovery
=> Update MIG agent to 20160126-1.c128226

nubis/puppet/files/purpose, nubis/puppet/purpose.pp
$> nubis-purpose (echo our purpose)
My Purpose
$> nubis-purpose "My Purpose" && "do something" (return true/false if purpose match)
do something
$> nubis-purpose "My Purpose" uptime (execute commands if purpose match)
08:27:01 up 35 min,  1 user,  load average: 0.00, 0.01, 0.05
Fixes #301
=> Create a small nubis-purpose wrapper script to work with our specified purpose

nubis/puppet/files/purpose
nubis-purpose "Some Purpose we are not" do something   ==>> successful status code
Fixes #305
=> Improve comments and handle a bit better the case

nubis/puppet/files/consul-bootstrap
=> Use HTTPS when bootstrapping consul

nubis/builder/packer-bootstrap.json
=> Move running packer-bootstrap back to where it belongs, before everything else

nubis/bin/packer-bootstrap
=> Upgrade ubuntu puppet to 3.8.6-1puppetlabs1

nubis/puppet/consul.pp
=> We don't even need Consul enabled, really, we deal with it ourselves

nubis/puppet/files/nubis-secret
=> nubis-secret: add --global option

nubis/puppet/files/consul-bootstrap
NOTE: Don't do this on a Consul server itself
Fixes #328
=> If user-data didn't contain an explcit Consul ACL token, ask credstash for one.

nubis/puppet/consul.pp
=> Upgrade Consul to v0.6.3

nubis/Puppetfile
=> Forgot to include module in Puppetfile

nubis/Puppetfile
- puppetlabs/apache 1.8.0 => 1.8.1
- jfryman/nginx     0.2.7 => 0.3.0
- thias/sysctl      1.0.4 => 1.0.6
Fixes #338
=> Update outdated puppet modules:

nubis/Puppetfile, nubis/puppet/consul.pp
=> Switch over to using envconsul puppet module

nubis/puppet/files/nubis-metadata, nubis/puppet/metadata.pp
Usage:
$> eval $(nubis-metadata)
$> nubis-metadata NUBIS_PURPOSE
Fixes #115
Fixes #251
=> Create nubis-metadata to access instance user-data

nubis/Puppetfile, nubis/puppet/consul.pp
=> Fix envconsul's tar related issues

nubis/Puppetfile, nubis/puppet/consul.pp
=> Switch over to our consul-do puppet package (unreleased)

nubis/files/confd/node_exporter.tmpl, nubis/files/confd/node_exporter.toml, nubis/puppet/node_exporter.pp
Set to 1 to enable, anything else to disable (off by default)
Fixes #350
=> Control node_exporter via consul:/environments/<ENV>/global/node_exporter/enabled

nubis/puppet/files/housekeeper
=> Cleanup /var/spool/mail/* and /var/cache/nubis/*

nubis/Puppetfile
=> Bump puppetlabs/firewall => 1.8.0, maestrodev/wget => 1.7.3

nubis/puppet/files/consul-bootstrap
=> Loop forever on startup for as long as we can't discover some Consul peers.

nubis/puppet/files/consul-bootstrap
=> Move Consul peer lookup and looping earlier in consul bootstraping

nubis/puppet/consul.pp
=> Upgrade consul to 0.6.4

nubis/puppet/credstash.pp
=> Upgrade Credstash to v1.10.0

nubis/puppet/files/consul-bootstrap
=> Wait until Consul has reported it's done bootstrapping before moving on

nubis/puppet/datadog.pp
=> Disable datadog on bootup, rely on confd to start it later, configured

nubis/puppet/files/consul-bootstrap
=> Don't restart confd ourselves, confd takes care of itself later.

nubis/puppet/files/profile.d_proxy.sh, nubis/puppet/files/rc.local
=> Ensure we always have a working proxy setup during boot

nubis/puppet/files/consul-bootstrap
=> Have curl retry during Consul bootstrap

index.md, nubis/Puppetfile, nubis/puppet/fluentd.pp
=> Fix the Ubnutu fluentd repo issue, getting us finally on td-agent 2.x on all platforms

nubis/puppet/datadog.pp
=> Bake proxies in our DataDog configs

nubis/puppet/fluentd.pp
=> Change user variables from USER|GROUP to TD_AGENT_USER|TD_AGENT_USER

nubis/puppet/consul.pp
=> Set leave_on_terminate = true

nubis/Puppetfile, nubis/puppet/ntp.pp
=> Install and enable NTPd by default

nubis/puppet/fluentd.pp
=> Previous fix was broken, this one is finally correct

nubis/puppet/files/fluentd.sysconfig
Also silences an annoying warning from our watchdog
Fixes #404
=> Use TD_AGENT_USER as recommended

nubis/puppet/release-upgrader-disable.pp
=> Remove ubuntu-release-upgrader-core on Ubuntu

nubis/puppet/node_exporter.pp
=> Fix missing containing directory missing

nubis/puppet/files/nubis-metadata
=> Silence errors if content is not valid shell

nubis/puppet/files/nubis-taint-reap, nubis/puppet/files/nubis-tainted
Controlled by 2 tunables:
* [consul]/environments/<env>/global/tainted/grace  (grace period, defaults to 1 hour if not set)
* [consul]/environments/<env>/global/tainted/delete (instances should self-terminate, not set by default)
Fixes #422
=> Final implementation of tainted resources, now enabled

nubis/puppet/files/nubis-tainted
=> [taint] Handle case where Consul isn't running (during packer runs)

nubis/puppet/files/nubis-metadata
=> Fix typo (missing fi)

nubis/puppet/files/housekeeper
See nubisproject/nubis-builder#181
=> Cleanup the housekeeper a little

nubis/files/confd/node_exporter.tmpl, nubis/puppet/node_exporter.pp
=> Strip top-level directory from the node_exporter tarball

nubis/Puppetfile, nubis/puppet/consul.pp
=> Upgrade envconsul to 0.6.1

nubis/puppet/consul.pp
=> Upgrade Consul to 0.7.0

nubis/Puppetfile
Change gets us default project tags in service definition
=> Upgrade to nubis_discovery v1.2.2

nubis/Puppetfile
=> Switch back to upstream fluentd puppet module from mrz-sft

nubis/Puppetfile
Waiting on nubisproject/nubis-puppet-storage#34
=> upgrade to nubis_storage v1.2.2

nubis/puppet/consul.pp
Also, while at it, turned off the update-check logic
Fixes #493
=> Disable Consul's remote-exec feature globally

nubis/puppet/files/nubis-availability-zone, nubis/puppet/files/nubis-region, nubis/puppet/metadata.pp
- nubis-region
- nubis-availability-zone
Fixes #495
=> Add 2 small tools for grabbing region and availability-zone

nubis/puppet/files/fluentd.sysconfig, nubis/puppet/fluentd.pp
=> Source our proxy settings file before starting fluentd

nubis/puppet/files/datadog-discover
=> When datadog is disabled, also disable the Consul service definition

nubis/puppet/files/nubis-taint-reap
=> nubis-tainted is noisy by default, ignore its output when we are running out of cron

nubis/puppet/fluentd.pp
And for convenience, drop fluent-cat in the PATH
=> [fluentd] Enable unix socket listener

nubis/puppet/nubis_users.pp
=> Bake in the current group names

nubis/files/confd/node_exporter.tmpl
=> Disable Consul node-exporter service check when disabled

nubis/puppet/atomic-rsync.pp, nubis/puppet/files/atomic-rsync
It's a generally useful rsync wrapper
Fixes #521
=> Include atomic-rsync in base images

nubis/puppet/files/nubis-secret
Usage:
```
$> nubis-secret set ssl/key SOMEVALUE
$> nubis-secret get ssl/key
Fixes #325
=> Add set ability to nubis-secret

nubis/puppet/fluentd.pp
=> Small upgrade for a refresh bugfix

nubis/puppet/files/gen-puppet.sh
Don't need this library so don't include it
=> We are not using this library so don't bother sourcing it

nubis/puppet/files/nubis-lib.sh
Fixes #533 of course this is all up for discussion
=> Not really used anymore? Is this still really needed?

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.1

nubis/Puppetfile
=> Include puppet module spantree/upstart@0.0.3

nubis/puppet/consul.pp
=> Don't restart Consul on config changes

nubis/puppet/files/profile.d_proxy.sh
=> no proxy for .service.consul URLs

nubis/puppet/files/nubis-tainted
=> Don't warn about taintedness when running under Packer

nubis/Puppetfile
=> Update puppet-fluentd for new package signing keys

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.2

nubis/Puppetfile
=> Upgrade to nubis_discovery v1.3.0

nubis/puppet/files/nubis-gen-puppet
=> Silence gen-puppet-watchdog cronjob

nubis/puppet/housekeeper.pp
=> Remove /root/.profile, it's not needed and causes tons of noise

nubis/files/confd/node_exporter.tmpl
=> Fix typo preventing exporting the purpose to metrics

nubis/puppet/consul.pp
=> Upgrade Consul to 0.7.4

nubis/Puppetfile
=> Upgrade datadog puppet module to 1.9.0

nubis/puppet/consul.pp
=> Upgrade to Consul v0.7.5

nubis/Puppetfile
(apache is still included, but comes from nubis_apache)
Fixes #604
=> Convert over to nubis_apache

nubis/Puppetfile
=> Upgrade to latest puppet-fluentd module

nubis/files/confd/mig-agent.cfg.tmpl
=> Explicitely configure MiG with our proxy service

nubis/builder/project.json
This is good after we merge this
https://github.com/nubisproject/nubis-builder/pull/213
**NOTE**: All things that rely on nubis-base will need nubis-builder updated or this will cause issues.
=> Remove no longer necessary variable

nubis/Puppetfile
=> Upgrade to nubis-apache v0.1.8

nubis/puppet/files/nubis-taint-reap
Can be disabled with
```
consulate kv set environments/<env>/global/tainted/delete 0
```
Fixes #447
=> Turn on taint reaping by default

nubis/Puppetfile
Our pull-requests have been merged
Fixes #632
=> Revert to upstream varnish module

nubis/builder/tests.json
=> Skip uploading test harness on ubuntu (disabled)

nubis/Puppetfile
Update vcsrepo to version 1.5.0, fixes part of #519
=> Update vcs repo module

nubis/Puppetfile
Updates mysql puppet module which fixes part of #591
=> Updating mysql puppet module to 3.10

nubis/puppet/files/gen-puppet.sh
=> Run initial /etc/nubis.d/01-gen-puppet in the background during bootup

nubis/puppet/consul.pp, nubis/puppet/files/consul-bootstrap
=> Upgrade to Consul 0.8.3

nubis/puppet/consul.pp, nubis/puppet/files/housekeeper
- We set disable_host_node_id = true in our config
- We cleanup /var/lib/consul/node-id after every build
Fixes #652
=> Make sure we use completely non-deterministic Consul host ids

nubis/bin/packer-bootstrap
=> Upgrade Ubuntu's Puppet to 3.8.7-1puppetlabs1

nubis/puppet/fluentd.pp
=> Upgrade fluentd-plugin-ec2-metadata to v0.0.16

nubis/puppet/files/housekeeper
=> Cleanup /var/lib/puppet/* after image build

nubis/puppet/files/gen-puppet.sh
Reverts nubisproject/nubis-base#650
=> Revert "Run initial /etc/nubis.d/01-gen-puppet in the background during bootup"

nubis/puppet/files/housekeeper
=> Correctly remove puppet files recursively

nubis/puppet/files/nubis-gen-puppet, nubis/puppet/nubis_users.pp
Also, run cron job every half-hour, but proprely randomly staggered
Fixes #579
=> Return success if we can't find /etc/puppet/yaml/nubis_users/common.yaml

nubis/Puppetfile
=> Upgrade to our latest version of the fork for a Prometheus bugfix

nubis/Puppetfile
=> Upgrade to v1.2.2

nubis/Puppetfile, nubis/puppet/files/consul-bootstrap
=> Substitute %%PURPOSE%% on startup

nubis/puppet/consul.pp
=> Upgrade consul-template to v0.19.0

nubis/Puppetfile
=> Upgrade nubis-puppet-apache to v0.1.10

nubis/puppet/consul.pp
=> Downgrade consul-template to v0.16.0

nubis/puppet/files/housekeeper
=> Retain puppet manifests on the instance

nubis/Puppetfile
=> Upgrade nubis_apache to v0.1.11

nubis/Puppetfile
=> Upgrade nubis-configuration to v1.3.1

nubis/puppet/proxy.pp
Yum truly doesn't like wildcards in this case
=> avoid pinning bind-utils

nubis/files/profile.d_proxy.sh
Makes the fallback slightly more preferable, but it's better than nothing (that will *never* work)
Fixes #681
=> Make sure to always set PROXY_* environment variables no matter what

nubis/Puppetfile
=> Upgrade to nubis-storage v1.2.4

nubis/files/profile.d_proxy.sh
=> Make sure we don't set proxy when we are expecting we can't

nubis/puppet/packages.pp
=> Install vim-enhanced

nubis/files/confd/conf.d/duo.toml, nubis/files/duo.sh, nubis/files/duo_sshd_config_runtime.pp, nubis/puppet/duo.pp
Split out post build duo config to a script and a puppet file so that we can actually bounce ssh properly
Fixes issue #756
=> Fix duo not working for cent 7 host

nubis/Puppetfile
=> Upgrade to puppet-user v1.4.3

nubis/Puppetfile, nubis/files/nubis-fluentd, nubis/puppet/consul.pp, nubis/puppet/credstash.pp, nubis/puppet/fluentd.pp
=> Final small update to using '@type' instead of the deprecated 'type'

nubis/Puppetfile
=> Upgrade nubis-puppet-apache to 0.1.15

nubis/files/confd/templates/node_exporter.tmpl
Fixes #585 and also needs nubisproject/nubis-builder#277 merged as well
=> Expose platform label

nubis/Puppetfile, nubis/terraform/inputs.tf, nubis/terraform/main.tf
=> Upgrade nubis-puppet-configuration to 1.3.4

nubis/files/nubis-taint
=> Allow system user to disable auto-tainting

nubis/files/nubis-taint-reap
In order, we try:
- aws autoscaling terminate-instance-in-auto-scaling-group
- aws ec2 terminate-instances
- shutdown -h now
Fixes #793
=> Try and use AWS APIs to gracefully terminate instances

nubis/files/nubis-cron, nubis/files/nubis-cron.logrotate, nubis/files/nubis-gen-puppet, nubis/puppet/cron.pp
=> Capture nubis-cron logs and ship them to ElasticSearch

nubis/files/nubis-metadata
=> [nubis-metadata] Detect usage of cloud-init and avoid AWS metadata API in that case

nubis/files/nubis-lib.sh, nubis/files/purpose
=> Use nubis-metadata

nubis/files/nubis-lib.sh
Slight refactor, eval nubis-metadata right off the bat and also create a new function that does search and replace in /etc/consul directory
=> Refactor nubis-lib

nubis/tests/run-tests
=> Pin bundler at 1.16.1

nubis/files/nubis-metadata
Closes #817
Closes mozilla-itcloud/maintenance-project/34
=> Expose instance identity document on host

nubis/files/profile.d_ps1.sh
=> Fix errors on login

nubis/files/gen-puppet.sh
=> Fixing gen-puppet to deal with errors

nubis/files/swap
=> Silence nubis-metadata output if output does not exist

nubis/Puppetfile
=> Bump nubis-puppet-nubis_users to v1.5.0

nubis/Puppetfile
Bump to version v1.3.6 fixes #859
=> Bump nubis-puppet-configuration tag

nubis/files/consul-bootstrap, nubis/files/nubis-fluentd
=> Fix metadata errors from fluent and consul startup scripts

nubis/files/swap
=> Use the metadata value for swap, if provided

nubis/files/consul-bootstrap
=> Add back %%PURPOSE%% %%STACK%% %%ENVIRONMENT%% substitution to /etc/consul/*

nubis/files/consul-bootstrap
=> Fix tyop preventing %%ENVIRONMENT%% expansion in /etc/consul
