nubisproject/nubis-base

.gitignore, Makefile, Puppetfile, packer/main.json, packer/release.json
Removes some extra code, and eventually will let us easliy pin at given
nubis-puppet releases
=> Convert base to use puppet-librarian itself too to pull in nubis-puppet

packer/consul-autojoin.sh, packer/main.json
Using user-data in instances to pass-in info:
CONSUL_SECRET=""
CONSUL_DC="us-west-1"
CONSUL_JOIN="some.host.name.to.bootstrap.with"
=> Add consul auto-discovery in packer template. Needs to move into puppet eventually

.gitignore, terraform/inputs.tf, terraform/main.tf, terraform/outputs.tf
For now, to get it to work, you need this in your variables file:
{
"aws_access_key": "XXX",
"aws_secret_key": "XXX",
"iam_instance_profile": "packer",
"key_name": "somekeyname",
"secret": "XXX Ask gozer XXX",
"consul": "XXX Ask gozer XXX"
}
=> add a simple terraform template to just launch one base image with consul lookups

nubis/packer/release.json, nubis/puppet/dnsmasq.pp, nubis/puppet/init.pp, nubis/terraform/inputs.tf
configured to forward DNS queries to Amazon's resolvers,
but intercept lookups for .consul and forward it to the
locally running consul agent.
=> Include DNSMasq in the base image

nubis/puppet/fluentd.pp
Should fix PR 86 and fix Issue #84
=> Fix ruby-dev name picking on Debian vs RH distros

nubis/Puppetfile
* datadog-datadog_agent (1.2.0 -> 1.3.0)
* puppetlabs-firewall (1.5.0 -> 1.6.0)
* puppetlabs-mysql (3.3.0 -> 3.4.0)
* puppetlabs-rabbitmq (5.1.0 -> 5.3.0)
* puppetlabs-stdlib (4.5.1 -> 4.6.0)
* puppetlabs-vcsrepo (1.2.0 -> 1.3.0)
* rtyler-jenkins (1.3.0 -> 1.4.0)
* stankevich-python (1.9.1 -> 1.9.4)
=> Upgrade puppet modules: (fixes nubisproject/nubis-puppet #41)

nubis/bin/packer-bootstrap
This manually grabs latest version from Amazon
=> Ubuntu repositories have very old versions of the ec2-ami-tools that just don't work at all.

nubis/bin/consul-autojoin.sh
- CONSUL_MASTER_ACL_TOKEN
- CONSUL_ACL_DEFAULT_POLICY=(allow)
- CONSUL_ACL_DOWN_POLICY=(extend-cache)
needed for nubisproject/nubis-consul#26
=> Add support for 3 more Consul Server bootstrap options:

nubis/bin/consul-autojoin.sh
@limed, you want to look at this
=> When we detect we are a Consul server, use NUBIS_PROJECT to build the DNS discovery name, don't hard-code .consul. Fixes #143

nubis/bin/consul-autojoin.sh
If passed to the instance via user-data, will be used by default by
Consul
Helps along nubisproject/nubis-consul#26
=> Add support for CONSUL_ACL_TOKEN in bootstrap.

nubis/puppet/consul.pp
This commit will fix the permission when consul-do gets installed, `wget` fetches it with mode `0644`, we should at least make sure that it gets `0755` so that users can call this utility
=> consul-do permission fix

nubis/bin/consul-autojoin.sh
The extra comma causes consul to not startup properly and thus causing consul and confd to fail
=> Extra comma causes consul to not startup

nubis/bin/consul-autojoin.sh
=> Use the Consul UI to discover peers first, then fallback on our DNS join endpoint

nubis/bin/consul-autojoin.sh
=> Use perl to remove the port number from hosts, as jq's split() is off limits for now

nubis/puppet/dnsmasq.pp
And this causes issues with the akamai-dns project, that's trying to
be a DNS service
Fixes #205
=> There is no reason to have dnsmasq bind on anything beside loopback

nubis/bin/packer-bootstrap
There is no need to be this restrictive here. We store no secrets here.
=> Adjust puppet directory permissions

nubis/bin/packer-bootstrap
Extracting the puppet modules onto the instance filesystem is now done in nubis-builder. See this [PR](https://github.com/nubisproject/nubis-builder/pull/103).
=> Remove extracting as it is now done in bulder

nubis/Puppetfile
=> Remove nubis-puppet-eip since this is used on a case by case basis

nubis/puppet/files/profile.d_proxy.sh, nubis/puppet/init.pp, nubis/puppet/proxy.pp
Logs from the proxy in nubis-lab:
Tested from amazon-linux:
1446155606.088     58 10.162.2.181 TCP_MISS/200 19829 GET http://www.google.com/ - DIRECT/173.194.121.16 text/html
Tested from Ubuntu:
1446156000.226     27 10.162.2.110 TCP_MISS/404 1918 GET http://www.google.com/404 - DIRECT/173.194.121.18 text/html
=> Add proxy configuration to base

nubis/puppet/mig.pp
This new URL will be used to host public agent packages.
=> Update mig agent version and use centralized public pkg dist URL

nubis/puppet/files/nubis-lib.sh
Cleanup nubis-lib in this PR we are doing the following
1. Moving top level variables that we populate via the aws metadata service to its own function
2. Added some functions that ease how we grab some commonly used values such as instance-id, eni-id etc etc
3. Cleanup log function to be more generic
4. Added a `die()` function
5. Remove the pre-req check, we assume that its there since it gets installed in base
=> nubis-lib cleanup

nubis/Puppetfile
Many upgrades, some cleanup removal, and 2 left pinned modules:
- puppetlabs-apt (2.x breaks apt-get update with fluentd + datadog)
- puppetlabs-concat (2.x breaks some of our modules, explicitely requesting < 2.x)
Fixes #272 and #209
=> Upgrade and cleanup our puppet modules

nubis/bin/packer-bootstrap, nubis/puppet/files/housekeeper
=> Move package puppet resource generation into houskeeper script, so it gets run at the end of every build, not just base.

nubis/puppet/nfs-disable.pp
=> Disable NFS related services on Amazon Linux (rpcbind & nfslock)

nubis/puppet/fluentd.pp
Right now, latest version of fluent-plugin-ec2-metadata requires just any
version of the fluentd gem. The latest versions of which ( 0.14.x ) now
require ruby > 2.0, which, unfortunately, isn't compatible with fluentd
on Ubuntu.
So, the correct solution would be to follow the 0.12.x branch of the
fluentd plugin.
Submitted takus/fluent-plugin-ec2-metadata#17 upstream
In the meantime, I've made a copy of the gem with just a clearer
set of requirements to use.
=> Work around problem with fluent-plugin-ec2-metadata on Ubuntu.

nubis/files/confd/node_exporter.toml
From /var/run/node_exporter to /usr/local/sbin/nubis_node_exporter
Fixes #428
=> Move node_exporter restart script somewhere always executable

nubis/files/confd/node_exporter.tmpl, nubis/puppet/files/node_exporter.init, nubis/puppet/files/node_exporter.upstart, nubis/puppet/node_exporter.pp
node_exporter reads metrics from .prom files dropped in /var/lib/node_exporter/metrics
Could be used for all sort of cute custom metrics, but for now, we drop
static (never-changing metadata metrics in there)
aws.prom:
aws{region="<region>",availability_zone="<az>",instance_type="<type>",ami_id="ami-XXXXXXXX",instance_id="i-XXXX"} 1
nubis.prom:
nubis{project="<project>",environment="<env>",account="<account>",purpose="<purpose>"} 1
Fixes #431
Note, also riding along is an upgrade to 0.12.0 from rc3
=> Enable textfile collector and create static metadata metrics

nubis/Puppetfile, nubis/puppet/files/housekeeper, nubis/puppet/files/nubis-taint, nubis/puppet/files/nubis-taint-reap, nubis/puppet/files/nubis-tainted, nubis/puppet/files/sshrc, nubis/puppet/files/svc-tainted.json, nubis/puppet/taint.pp
Implement tracking of tainted instances and self-termination
First initial implementation, consisting of:
* ssh PAM.d session hook to invoke /usr/local/sbin/nubis-taint
* /usr/local/sbin/nubis-taint PAM helper to just mark an instance as tainted on ssh logins
* /.tainted as a flag file indicating an instance has been tainted
* /usr/local/bin/nubis-tainted to check on taintedness (don't ever look for /.tainted yourself )
* /etc/consul/svc-tainted.json to expose to consul tainted nodes's status
* /usr/local/sbin/nubis-taint-reap to self-terminate if:
* we are tainted
* we are old enough ( 2 day grace period for now )
* nobody is currently logged-in
* [consul] environments/$NUBIS_ENVIRONMENT/global/delete_tainted feature enable flag (off by default)
* hourly /usr/local/sbin/nubis-taint-reap …
=> [tainted] Implement tracking of tainted instances and self-termination

nubis/puppet/files/nubis-metadata
Either using a stale version of the system's cache, or failing that,
caching their own version of it.
This was discovered with nubis-tainted
Fixes #449
=> [metadata] Make sure non-root users can use nubis-metadata correctly

nubis/builder/tests.json, nubis/tests/Gemfile, nubis/tests/Rakefile, nubis/tests/run-tests, nubis/tests/spec/services_spec.rb, nubis/tests/spec/spec_helper.rb, nubis/tests/spec/timezone_spec.rb, nubis/tests/spec/users_spec.rb
This has just some simple sample tests, nothing major, but they all should pass
Road for implementing more tests is ahead.
Also, eventually, probably worth moving some of this logic into nubis-builder
itself, to simplify the required scaffolding
Fixes #133
=> Add initial working skeleton for running serverspec tests during AMI build

nubis/puppet/files/consul-bootstrap
This way, we can expose stuff as tags if we want, for instance
- %%ENVIRONMENT%% => $NUBIS_ENVIRONMENT
- %%STACK%% => $NUBIS_STACK
- %%PROJECT%% => $NUBIS_PROJECT
=> Just like confd does, do some runtime pattern substitution for Consul service checks

nubis/Puppetfile
Gets us the default %%PROJECT%% service tags
=> Upgrade puppet-nubis_discovery to v1.2.2

nubis/Puppetfile
Reverts nubisproject/nubis-base#488
Failed to verify where my fork was at, and it wasn't on tip of master, so this will break stuff.
=> Revert "Switch back to upstream fluentd puppet module from mrz-sft"

nubis/Puppetfile
Exceptions for dependencies issues were:
- puppetlabs-concat
- puppetlabs-staging (and conflicting with nailu/staging too)
- puppetlabs-apt
Fixes #489
=> Upgraded most puppet modules that were outdated

nubis/puppet/files/datadog-discover
Heuristics a bit:
When the Datadog API keys contains 'DISABLED', don't bother running it
It chews up lots of CPU and is very log-noisy when its API key is invalid
Fixes #496
=> Don't run the datadog agent when its disabled

nubis/puppet/files/fluentd.sysconfig, nubis/puppet/fluentd.pp
Each event forwarded now also gets:
- vpc_id
- subnet_id
- private_ip (why not? correlation in client logs)
- ami_id (historical tracking)
- mac (its available and could be interesting if ami_ids ever get reused?)
- project (value of NUBIS_PROJECT)
- stack (value of NUBIS_STACK)
- purpose (value of NUBIS_PURPOSE)
Just makes for richer events in general
Fixes #502
=> Include more information in each forwarded log event

nubis/puppet/files/svc-node-exporter.json, nubis/puppet/node_exporter.pp
This way, we have an actual service watching the health of our node_exporters
Prometheus will make use of that for its node discovery
Fixes #510
=> Expose node-exporter as a Consul service

nubis/puppet/files/nubis-network-ips, nubis/puppet/files/profile.d_proxy.sh, nubis/puppet/proxy.pp
Given how our networks are built, we safely assume we can just take our
network, and expand it to a /24 to get all IPs of our potential peers
Fixes #513
=> Correctly populate the NO_PROXY variable with IPs in our subnet.

nubis/puppet/confd.pp, nubis/puppet/cron.pp, nubis/puppet/files/nubis-cron, nubis/puppet/fluentd.pp, nubis/puppet/node_exporter.pp, nubis/puppet/nubis_users.pp, nubis/puppet/taint.pp
Use like this:
nubis-cron <name-of-job> some command to run
It will expose 3 metrics for the job
```
nubis_cron_start{cronjob="<name-of-job>"} 1481656261
nubis_cron_end{cronjob="<name-of-job>"} 1481656265
nubis_cron_status{cronjob="<name-of-job>"} 0
```
Fixes #459
=> Create nubis-cron, prometheus wrapper for cronjobs

nubis/puppet/files/consul-bootstrap
As there can be a cluster event (leadership change) during our bootup.
Fixes #555
=> Don't assume we can always sucessfully find peers once Consul is up, retry

nubis/puppet/files/nubis-cron
bash -c "$@" turns into bash -c "command" "-argments"
bash -c "$*" turns into bash -c 'command -arguments'
Second option is correct
=> Fix small *bad* tyop

nubis/puppet/files/housekeeper
Otherwise, it's possible we leave busted/invalid stuff behind
Fixes #567
=> Cleanup /var/lib/node_exporter/metrics during image housekeeping

nubis/puppet/files/purpose
-z "$*" will work with multiple arguments, -z "$@" won't
Fixes #569
=> Use $* as it should have been

.travis.yml
This gets us newest nubis-builder with spot instances and no more aws cli
Fixes #593
=> Upgrade nubis-travis to v1.3.5

nubis/puppet/fluentd.pp
0.0.16 isn't on the gem repositories yet.
Un-Breaks #658
=> Fix: Downgrade fluent-plugin-ec2-metadata to 0.0.15

nubis/puppet/confd.pp
Otherwise, we don't get the needed /etc/nubis.d/confd startup script
Fixes #668
=> Make sure to inculde nubis_configuration at least once

nubis/puppet/nubis_users.pp
Renamed to /etc/nubis.d/00-gen-puppet
Fixes #679
=> Move gen-puppet startup earlier in the boot process

nubis/Puppetfile
=> Upgrade to nubis-puppet-discovery v1.3.2 to silence a Puppet warning

nubis/puppet/files/node_exporter.init, nubis/puppet/files/node_exporter.upstart, nubis/puppet/files/nubis-cron, nubis/puppet/node_exporter.pp
Upgrades node exporter and remove metrics we don't care to scrape for. Includes a nubis-cron fix that since upgrading to v0.15.0 causes issues with it
PR fixes issue #737 #720 and #721
=> Upgrades node_exporter to v0.15.0

nubis/files/confd/conf.d/duo.toml
Otherwise, we see messages like this and DUO is inoperating
```
sshd[3400]: /etc/duo/pam_duo.conf must be readable only by user 'root'
```
Fixes #748
=> /etc/duo/pam_duo.conf needs to be 0600 for duo to be happy

nubis/Puppetfile
[Full Changelog](https://github.com/nubisproject/nubis-puppet-storage/compare/v1.2.4...v1.2.5)
**Closed issues:**
- EFS mount targets don't need the AZ prefix anymore [\#46](https://github.com/nubisproject/nubis-puppet-storage/issues/46)
- Generate Prometheus metric exposing the EFS fsid we are using [\#45](https://github.com/nubisproject/nubis-puppet-storage/issues/45)
- Remove hardcoded value [\#36](https://github.com/nubisproject/nubis-puppet-storage/issues/36)
**Merged pull requests:**
- EFS mount targets don't need AZ prefix anymore [\#49](https://github.com/nubisproject/nubis-puppet-storage/pull/49) ([gozer](https://github.com/gozer))
- Create Prometheus metric exposing the EFS id [\#48](https://github.com/nubisproject/nubis-puppet-storage/pull/48) …
=> Upgrade nubis-puppet-storage to v1.2.5

nubis/files/swap, nubis/puppet/swap.pp
Can be configured in user-data with NUBIS_SWAP_SIZE_MEG.
Defaults to 512 Megs
Disable completely by setting it to 0
Also, tune down swapiness to 10
Fixes #778
=> Handle swap creation for instances at boot time

nubis/files/nubis-metadata
This will aid in troubleshooting errors on boot to know who called
nubis-metadata and triggered an error.
=> Expose caller to nubis-metadata

nubis/puppet/mig.pp
This change refers to new MIG agent binaries that I have uploaded to the S3 bucket that Puppet is already set to read from.
=> New MIG agent release

nubis/puppet/mig.pp
Reverts nubisproject/nubis-base#883
This is causing builds to fail with the following error:
Error: 'wget --verbose --output-document="/tmp/mig.rpm" "https://s3.amazonaws.com/mozopsecrepo2/mig-public/it-nubis/mig-agent-20180803_0.e8eb90a.prod-1.x86_64.rpm"' returned 8 instead of one of [0]
When I attempt to view the file directly I get:
Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>8C5B0637D80186C3</RequestId><HostId>XIVacbfClnhCPz5q4S2EQsC4T9DaUjW4BSA9LqSDJkuFZrNrRWzrHBs7M9rJcAOO9grhkcOYcMk=</HostId></Error>
Let me know when you have fixed this issue and I will re-merge this build. For now I am trying to get a patch release out the door and this issue is blocking that release.
=> Revert "New MIG agent release"
